# Generated by Django 3.2.2 on 2021-05-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact',
            new_name='number',
        ),
    ]
